manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: PandaKBLab
      url-base: https://github.com/PandaKBLab
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 354cff9cc14e26bbf62d34ae72f24bccbaa69b0b
      import: app/west.yml
    - name: zmk-for-PandaKB
      remote: PandaKBLab
      revision: PandaKB_Lily58
  self:
    path: config
